# permissions for end users to edit yourcustomresources.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: yourcustomresource-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: your-operator
    app.kubernetes.io/part-of: your-operator
    app.kubernetes.io/managed-by: kustomize
  name: yourcustomresource-editor-role
rules:
- apiGroups:
  - app.example.com
  resources:
  - yourcustomresources
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - app.example.com
  resources:
  - yourcustomresources/status
  verbs:
  - get
